# -*- coding: utf-8 -*-
"""lab 01 practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qOV55_UucGQU97k7A_sntALlzG4ACqvY
"""

my_first_var = ((118+11*2)/(9-2))
print(my_first_var)

def arithmetic(i):
  return ((3 * (i + 2)) - 5)
arithmetic(-10)

def triple(y):
  return (y*3)

def avg(x,y):
  return ((x + y)/2)

def combine(x,y):
  return(avg(x,triple(y)))

triple(10), avg(5,25), combine(6,5)

def first(c):
  return c[0]

def first_last(c):
  return c[0], c[-1]

def middle(c):
  return c[1:-1]

w= [1,2,3,4,5]
first(w), first_last(w), middle(w)

def swap(c):
  new_list, hold_this = c.copy(), [] # This creates a copy of the list c, which is called new_list.  Your function should work with this list instead of the list c which is passed to the function.
  hold_this.append(new_list[0])
  new_list[0], new_list[-1] = new_list[-1], hold_this[0]
  return new_list

swap([0,1,2,3,4,5])

def absolute_value(x):
  if x == 0:
    return 0
  elif x > 0:
    return x
  elif x < 0:
    return (x * -1) # Put your return value here.

absolute_value(8), absolute_value(0), absolute_value(-8)

def indicator(lower,upper,n):
  if lower <= n and n <= upper:
    return 1
  else:
    return 0 # Put your return value here.

indicator(3,7,2), indicator(-3,9,8)

def trunc_max(x,y):
  if 0 < x or 0 < y:
    if y < x:
      return x
    else:
      return y
  else:
    return 0 # Put your return value here.

trunc_max(3,-5), trunc_max(2,7), trunc_max(-173, -21)