# -*- coding: utf-8 -*-
"""lab 02 homework

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19A29coDCRGtJKvZPV67KJYXgozA8guNh

# **Lab 2 - Introduction to Python programming II**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab2"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="Benjamin"

last_name="Andreasen"

# Enter your Math 215 section number in between the quotation marks.

section_number="001"

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="bca44"

"""**Problem 1**"""

first_elem=1   # Replace the value of 0 with the number described in Problem 1.

"""**Problem 2**"""

def sum_list(L):
  sum = 0
  for i in L:
    sum += i
  return sum # Put your return value here.

"""**Problem 3**"""

def list_relu(L):
  new_list = [ ]
  for i in L:
    if i >= 0:
      new_list.append(i)
    elif i < 0:
      new_list.append(0)
  return new_list # Put your return value here.

"""**Problem 4**"""

import numpy as np  # Importing NumPy

my_var = (np.exp(5.0) - np.log(np.sqrt(5.0)))/(np.exp(np.cos(3.0)))   # Replace the value of 0 with the required value from Problem 4.

"""**Problem 5**"""

v, u, w = np.array([1,3,-2,4,5]), np.array([1,1,-2,1,1]), np.array([1,0,1,0,1])

my_vect_var= ((np.dot(v,u)/np.dot(u,u)) * u) + (((np.dot(v,w))/np.dot(w,w))*w)   # Replace the value of 0 with the required value from Problem 5.

"""**Problem 6**"""

def first_rpt(M):
  new_matrix=M.copy()  # Remember to create a copy of your matrix.  After this lab you'll need to remember to do it on your own.
  for i in range(len(new_matrix)):
    if i > 0:
      new_matrix[i] = new_matrix[0]
  return new_matrix # Put your return value here.

"""**Problem 7**"""

def matrix_sum(M):
  sum = 0
  for i in M: #i in M means i is each row in matrix M
    for j in i: #j in i means j is each value in row i
      sum += j #add that value to our sum placeholder
  return sum #return that sum value, which should have looped through every value in every row

"""**Problem 8**"""

def make_long_list(x):
  i, long_list = 1, []
  while i <= 100:
    long_list.append((x)**i)
    i += 1
  return long_list

long_list = make_long_list(.5) # Replace the value of 0 with the required list from Problem 8.

"""**Problem 9**"""

def make_very_long_list(x):
  i, j, very_long_list = 1, 1, []
  while i < 100:
    j = 1
    while j <= 3:
      very_long_list.append((j)**i)
      j += 1
    i += 1
  return very_long_list


very_long_list = make_very_long_list(1)   # Replace the value of 0 with the required list from Problem 9.

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.
"""