# -*- coding: utf-8 -*-
"""lab 07 homework

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPhRfm9HmaA_K60WtFUHBjesZnT_N2D9

#**Lab 7 - Least squares II**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab7"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="Your first name goes here"

last_name="Your last name goes here"

# Enter your Math 215 section number in between the quotation marks.

section_number="Your Math 215 section number goes here"

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="Your BYU NetID goes here"

"""**Import the data set**

The simplest way to load the data into Colab is to first download it as a .csv file to your local computer by clicking the link

https://drive.google.com/uc?export=download&id=1iFTaBmnv1X66BO9cV_RP7OxvUr9dNJ-l

This will allow you to download the data as a .csv file.  In the top left corner of this screen you should see a little file folder icon.  Selecting it opens a new window to the left of the notebook with three tabs: "Upload", "Refresh", and "Mount Drive".  Select "Upload". This should bring up a window that allows you to select the file "Lab7data" from your local machine, which will upload the file to your notebook. You will need to do this again if you decide to close your notebook and reopen it at a later time.

Once you've uploaded your file, convert it to a NumPy array called "signal_data" by executing the following cell.
"""

import numpy as np
import pandas as pd

df = pd.read_csv('Lab7data.csv')
signal_data=df.values
signal_data

"""**Problem 1**"""

T=signal_data[:, 0]

Y=signal_data[:, 1]

import matplotlib.pyplot as plt

# Create the plot here of the data in the vectors T and Y.

"""**Problem 2**"""

# This function returns the row [1,cos(t),sin(t), cos(2*t), sin(2*t) , ... , cos(n*t), sin(n*t)] of our matrix X.

def row_func(t,n):
  L = [f(t * k) for k in range(1,n+1) for f in [np.cos, np.sin]]
  L.insert(0, 1)
  return L

"""**Problem 3**"""

# This function returns the matrix X, which we call the design matrix.

def design_matrix(n):
  L_matrix = [row_func(t, n) for t in T]
  return np.array(L_matrix)

"""**Problem 4**"""

X2 = design_matrix(2)

"""**Problem 5**"""

Xt = np.transpose(X2)

# Replace all of the 0 values with the NumPy matrices and vectors requested in Problem 5.

normal_coef2 = np.dot(Xt, X2)

normal_vect2 = np.dot(Xt, Y)

beta2 = np.linalg.solve(normal_coef2, normal_vect2)

"""**Problem 6**"""

def f2(t):
    # Compute the row vector for t with n=2 using row_func function
    row_vector = np.array(row_func(t, 2))

    # Compute f2(t) by taking the dot product of beta2 and the row vector
    result = np.dot(beta2, row_vector)

    return result

"""**Problem 7**"""

vf2 = np.vectorize(f2)
plt.plot(T, Y, ".")
plt.plot(T, vf2(T), "b-")
plt.show()

"""**Problem 8**"""

# Step 1: Calculate predicted values
predicted_values = np.dot(X2, beta2)

# Step 2: Calculate residuals
residuals = predicted_values - Y

# Step 3: Square the residuals
squared_residuals = residuals**2

# Step 4: Calculate mean squared error
MSE2 = np.mean(squared_residuals)

"""**Problem 9**"""

# Replace the 0 values with the values requested in Problem 9.  Remember to copy the decimal values from your practice notebook, not the formulas you used to compute them.

MSE10 = 0.009348751458203413

pred10 = 0.5087757565416515

"""**Problem 10**"""

# Replace the 0 values with the values requested in Problem 10.  Remember to copy the decimal values from your practice notebook, not the formulas you used to compute them.

MSE100 = 0.0014547562364331276

pred100 = 0.5089902472113171

"""**Problem 11**"""

# Replace the 0 values with the values requested in Problem 11.  Remember to copy the decimal values from your practice notebook, not the formulas you used to compute them.

MSE1000 = 1.9961406113768612e-28

pred1000 = -14.192461430169898

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.
"""